### PR TITLE
Prepare for pystac 1.0

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/microsoft/planetary-computer-sdk-for-python/issues/13

### CODE REVIEW

**Comment by TomAugspurger** [comment]
The CI failure is an issue with the sample Item we have in our tests. We can reproduce the failure with just `pystac`.

```python
In [3]: pystac.read_file("tests/data-files/sample-item.json").to_dict()
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
~/miniconda3/envs/pystac-1.0/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1353             try:
-> 1354                 h.request(req.get_method(), req.selector, req.data, headers,
   1355                           encode_chunked=req.has_header('Transfer-encoding'))

~/miniconda3/envs/pystac-1.0/lib/python3.8/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1251         """Send a complete request to the server."""
-> 1252         self._send_request(method, url, body, headers, encode_chunked)
   1253

~/miniconda3/envs/pystac-1.0/lib/python3.8/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1297             body = _encode(body, 'body')
-> 1298         self.endheaders(body, encode_chunked=encode_chunked)
   1299

~/miniconda3/envs/pystac-1.0/lib/python3.8/http/client.py in endheaders(self, message_body, encode_chunked)
   1246             raise CannotSendHeader()
-> 1247         self._send_output(message_body, encode_chunked=encode_chunked)
   1248

~/miniconda3/envs/pystac-1.0/lib/python3.8/http/client.py in _send_output(self, message_body, encode_chunked)
   1006         del self._buffer[:]
-> 1007         self.send(msg)
   1008

~/miniconda3/envs/pystac-1.0/lib/python3.8/http/client.py in send(self, data)
    946             if self.auto_open:
--> 947                 self.connect()
    948             else:

~/miniconda3/envs/pystac-1.0/lib/python3.8/http/client.py in connect(self)
   1413
-> 1414             super().connect()
   1415

~/miniconda3/envs/pystac-1.0/lib/python3.8/http/client.py in connect(self)
    917         """Connect to the host and port specified in __init__."""
--> 918         self.sock = self._create_connection(
    919             (self.host,self.port), self.timeout, self.source_address)

~/miniconda3/envs/pystac-1.0/lib/python3.8/socket.py in create_connection(address, timeout, source_address)
    786     err = None
--> 787     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
    788         af, socktype, proto, canonname, sa = res

~/miniconda3/envs/pystac-1.0/lib/python3.8/socket.py in getaddrinfo(host, port, family, type, proto, flags)
    917     addrlist = []
--> 918     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    919         af, socktype, proto, canonname, sa = res

gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-3-a9a79a40640a> in <module>
----> 1 pystac.read_file("tests/data-files/sample-item.json").to_dict()

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/item.py in to_dict(self, include_self_link)
    867             "properties": self.properties,
    868             "geometry": self.geometry,
--> 869             "links": [link.to_dict() for link in links],
    870             "assets": assets,
    871         }

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/item.py in <listcomp>(.0)
    867             "properties": self.properties,
    868             "geometry": self.geometry,
--> 869             "links": [link.to_dict() for link in links],
    870             "assets": assets,
    871         }

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/link.py in to_dict(self)
    247         d: Dict[str, Any] = {"rel": self.rel}
    248
--> 249         d["href"] = self.get_href()
    250
    251         if self.media_type is not None:

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/link.py in get_href(self)
    119             href = cast(Optional[str], self.target)
    120
--> 121         if href and is_absolute_href(href) and self.owner and self.owner.get_root():
    122             root = self.owner.get_root()
    123             rel_links = [

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/stac_object.py in get_root(self)
    200         if root_link:
    201             if not root_link.is_resolved():
--> 202                 root_link.resolve_stac_object()
    203                 # Use set_root, so Catalogs can merge ResolvedObjectCache instances.
    204                 self.set_root(cast(pystac.Catalog, root_link.target))

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/link.py in resolve_stac_object(self, root)
    211                         stac_io = pystac.StacIO.default()
    212
--> 213                 obj = stac_io.read_stac_object(target_href, root=root)
    214                 obj.set_self_href(target_href)
    215                 if root is not None:

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/stac_io.py in read_stac_object(self, source, root, *args, **kwargs)
    223             contained in the file at the given uri.
    224         """
--> 225         d = self.read_json(source, *args, **kwargs)
    226         href = source if isinstance(source, str) else source.get_absolute_href()
    227         return self.stac_object_from_dict(d, href=href, root=root, preserve_dict=False)

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/stac_io.py in read_json(self, source, *args, **kwargs)
    194             given source.
    195         """
--> 196         txt = self.read_text(source, *args, **kwargs)
    197         return self.json_loads(txt)
    198

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/stac_io.py in read_text(self, source, *_, **__)
    276             if href is None:
    277                 raise IOError(f"Could not get an absolute HREF from link {source}")
--> 278         return self.read_text_from_href(href)
    279
    280     def read_text_from_href(self, href: str) -> str:

~/miniconda3/envs/pystac-1.0/lib/python3.8/site-packages/pystac/stac_io.py in read_text_from_href(self, href)
    293         if parsed.scheme != "":
    294             try:
--> 295                 with urlopen(href) as f:
    296                     href_contents = f.read().decode("utf-8")
    297             except HTTPError as e:

~/miniconda3/envs/pystac-1.0/lib/python3.8/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223
    224 def install_opener(opener):

~/miniconda3/envs/pystac-1.0/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    523
    524         sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525         response = self._open(req, data)
    526
    527         # post-process response

~/miniconda3/envs/pystac-1.0/lib/python3.8/urllib/request.py in _open(self, req, data)
    540
    541         protocol = req.type
--> 542         result = self._call_chain(self.handle_open, protocol, protocol +
    543                                   '_open', req)
    544         if result:

~/miniconda3/envs/pystac-1.0/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~/miniconda3/envs/pystac-1.0/lib/python3.8/urllib/request.py in https_open(self, req)
   1395
   1396         def https_open(self, req):
-> 1397             return self.do_open(http.client.HTTPSConnection, req,
   1398                 context=self._context, check_hostname=self._check_hostname)
   1399

~/miniconda3/envs/pystac-1.0/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1355                           encode_chunked=req.has_header('Transfer-encoding'))
   1356             except OSError as err: # timeout error
-> 1357                 raise URLError(err)
   1358             r = h.getresponse()
   1359         except:

URLError: <urlopen error [Errno -2] Name or service not known>
```

AFAICT, we don't actually use `links` anywhere in this library (does that sound right @kshepard?). So 3f38be04e800e9d2cecb050acafce22c892d097d just removes them from our sample item.

**Comment by TomAugspurger** [comment]
If https://github.com/stac-utils/pystac/pull/500 is merged before pystac 1.0, we'll want to bump our python_requires.

**Comment by kshepard** [comment]
> AFAICT, we don't actually use `links` anywhere in this library (does that sound right @kshepard?)

That's correct, should be safe to use an empty list as you've done here :+1:

**Comment by TomAugspurger** [comment]
I'm going to merge this and put a release candidate up on PyPI.

**Pull request merged**
