### PR TITLE
Include license in sdist

### PR DESCRIPTION
**Pull request by TomAugspurger**
Currently, only the wheels had the LICENSE file.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Make some bigger changes. Turns out we couldn't install from the sdist, since it relied on the presence of files like requirements.txt.

I've transitioned the project to use a static setup.cfg file instead. A `setup.py` is kept around just so that `pip install -e .` works for development.

**Comment by TomAugspurger** [comment]
@kshepard @lossyrob I'll plan to merge this later today unless I hear otherwise.

**Comment by lossyrob** [comment]
@TomAugspurger thanks for the ping; this looks good to me, I have some general questions about replacing setup.py with .cfg. I'm very used to the setup.py method and not familiar with the .cfg approach, why that enables certain installation, or what the potential downsides are to doing this approach. One thing I like about a requirements file is that I can set up the virtualenv with dependencies for the development environment pretty simply, without installing the codebase - but that's pretty minimal. I'm curious if you have thoughts about when a cfg should be used over setup.py - do you always prefer the cfg and a relatively empty setup.py? If there were no setup.py (as I've seen in some projects), is there an alternate way we setup the dev virtualenv with the dependencies?

**Comment by TomAugspurger** [comment]
> One thing I like about a requirements file is that I can set up the virtualenv with dependencies for the development environment pretty simply, without installing the codebase - but that's pretty minimal.

FWIW, the *development* dependencies are still in a requirements file. It doesn't get you an entirely functional environment though, since it would lack the required dependencies.

>  If there were no setup.py (as I've seen in some projects), is there an alternate way we setup the dev virtualenv with the dependencies?

The workflow will be the same as https://github.com/microsoft/planetary-computer-sdk-for-python/blob/535436888ba47d21515766b87fac5dc073c1257e/scripts/cibuild#L22-L23.

"Editable" installs are not currently standardized by a PEP (see https://discuss.python.org/t/specification-of-editable-installation/1564). So pip doesn't really know what to do with them. That's why we have the mostly empty `setup.py`, so that setuptools can take over and handle things. A bit of a mess!

Functionally though, this should be

1. An improvement for users building from sdist since they can actually build from an sdist :)
2. No change for developer's workflow.

**Comment by lossyrob** [comment]
Gotcha - understood that this is a general no-op plus improvement for this change, was curious about the more general approach (e.g. I might change libraries like PySTAC with a similar change to allow sdist installs etc).

Either way, +1 from me

**Review by lossyrob — APPROVED** [review]

**Comment by TomAugspurger** [comment]
I'm always happy to complain about packaging :)

> I might change libraries like PySTAC with a similar change to allow sdist installs etc

I should have mentioned, a possibly simpler solution would have been to include the `requirements.txt` in the source distribution. But I can never figure out the incantation to get that to work (I think it involves a `MANIFEST.in` file + something else). That would have been sufficient for editable installs.

My preference for this setup is it avoids executing arbitrary Python code in a simple `pip install --no-binary <package>`. Just cleaner.

Something like this should work for pystac. I suspect it wouldn't for stactools, which does rely on executing Python code to make the Subpackages.

**Pull request merged**
